### ISSUE TITLE
Expose the app directly & allow setting UID/GID

### ISSUE THREAD

**Issue by grOGH** [janeczku/docker-calibre-web#5]
A few minor suggestions for this stellar app:

- Let the application server bind directly to 0.0.0.0 instead of localhost and expose port 8083. Some of us run our own SSL reverse proxy in another container that we'd like to point directly to the application. (Proxying to the included nginx from a subdirectory creates issues with static resources). Having an env variable toggling this behavior (and not starting the included nginx at all) would be amazing.

- Allow us to set the UID/GID that the application uses to define the user similar to how the linuxserver.io folks do it so it doesn't run as root.

**Comment by janeczku** [comment]
@grOGH @Kyosfonica I don't have to time to actively maintain this image. I recommend to check out the image here: https://github.com/Technosoft2000/docker-calibre-web
