### ISSUE TITLE
Hostname configuration

### ISSUE THREAD

**Issue by flexguse** [janeczku/docker-calibre-web#6]
Hi, 
I set up docker-calibre-web using a mounted folder from my docker host. The container starts, reads my library and looks almost fine.
Almost, because every time I try to log in, edit the configuration etc. the wrong hostname is set for redirection. It seems the docker container ID is used and not the the hostname I put into my local DNS server.

How can I configure the hostname of docker-calibre-web?

Cheers,
Christoph

**Comment by flexguse** [comment]
This error seems to be specific for my setup. I use the Traefik reverse proxy. Everytime calibre-web does a redirect (login / configuration / logout) it uses the docker ID of the reverse proxy instead of the hostname.

**Comment by janeczku** [comment]
Maybe give this a try: https://github.com/janeczku/docker-calibre-web#running-behind-additional-reverse-proxy
