### ISSUE TITLE
Unable to set Calibre Library path

### ISSUE THREAD

**Issue by MontyJ** [janeczku/docker-calibre-web#7]
Installing using QNAP Container Station. QNAP TS-251, Firmware V4.3.3
Installation works ok, am able to start config at http://192.168.x.x:32769/config ok.
Leaving all other basic options set to default, enter the "Location of Calibre database" as:
/share/Backups/Calibre_Libraries/02-Fiction
or
/share/Backups/Calibre_Libraries/02-Fiction/
or
/share/CACHEDEV1_DATA/Calibre_Libraries/02-Fiction
or
/share/CACHEDEV1_DATA/Calibre_Libraries/02-Fiction/

All the variations of the library path produce the error: DB location is not valid, please enter correct path

The path is correct. The "metadata.db" and "metadata_db_prefs_backup.json" files are in the "02-Fiction" folder, along with all the author folders.

I have checked the path with pwd and did a direct copy/paste to ensure no typo's. Still get error and unable to set library path. Tried with Chrome and Firefox browsers, same error.

**Comment by janeczku** [comment]
@MontyJ  I don't have to time to actively maintain this image. I recommend to check out the image here: https://github.com/Technosoft2000/docker-calibre-web
