### ISSUE TITLE
Unable to set SSL configuration DEFAULT_HOST_CONF error

### ISSUE THREAD

**Issue by Kyosfonica** [janeczku/docker-calibre-web#8]
If I set the environtment variables to enable SSL the container is unable to start.
The error it shows is "sed: can't read DEFAULT_HOST_CONF: No such file or directory"
I have mounted the certs folder to /etc/nginx/ssl as a volume and set the env variables to the certs filenames but I am not able to make it work.

**Comment by janeczku** [comment]
@Kyosfonica I don't have to time to actively maintain this image. I recommend to check out the image here: https://github.com/Technosoft2000/docker-calibre-web
